framework:
    secret: '%env(APP_SECRET)%'
    
    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file