name: Symfony + PHP - WR506D

on:
  push:
    branches: [ "develop","main" ]
  pull_request:
    branches: [ "develop","main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json, mbstring

      - name: Copy .env.test.local
        working-directory: ./application
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ./application/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('./application/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install Dependencies
        working-directory: ./application
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Create Database
        working-directory: ./application
        run: |
          mkdir -p data
          touch data/database.sqlite
          chmod 777 data/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        working-directory: ./application
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/data/database.sqlite"
        run: vendor/bin/phpunit

      - name: Run PHP_CodeSniffer
        working-directory: ./application
        run: vendor/bin/phpcs --standard=PSR2 src/
